// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/commands/[name].tsx";
import * as $1 from "./routes/commands/index.tsx";
import * as $2 from "./routes/github.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/invite.ts";

const manifest = {
  routes: {
    "./routes/commands/[name].tsx": $0,
    "./routes/commands/index.tsx": $1,
    "./routes/github.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/invite.ts": $4,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
