// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/commands/[name].tsx";
import * as $2 from "./routes/commands/index.tsx";
import * as $3 from "./routes/github.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/invite.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/commands/[name].tsx": $1,
    "./routes/commands/index.tsx": $2,
    "./routes/github.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/invite.ts": $5,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
